# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [9]:
import numpy as np

mat_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
mat_b = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
mat_c = mat_a + mat_b

mat_d = mat_c @ np.array([1, 2, 3])

mat_e = mat_c.T

mat_f = np.linalg.inv(mat_c)

print(mat_c)

[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]


### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [15]:
import numpy as np

m = np.array([[2, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(m)

print("Собственные значения:", eigenvalues)
print("Собственные векторы:")
print(eigenvectors)


Собственные значения: [1. 4.]
Собственные векторы:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [38]:
import numpy as np

def find_matrix_with_determinant(size, target_det=1, max_attempts=10000):
    """
    Находит случайную матрицу заданной размерности с определителем равным target_det.
    
    :param size: Размерность квадратной матрицы (size x size)
    :param target_det: Целевое значение определителя (по умолчанию 1)
    :param max_attempts: Максимальное количество попыток (по умолчанию 10,000)
    :return: Найденная матрица или None, если матрица не найдена
    """
    for _ in range(max_attempts):
        # Генерируем случайную матрицу с целыми числами от 1 до 10
        matrix = np.random.randint(1, 10, (size, size))
        det = round(np.linalg.det(matrix))
        if det == target_det:
            return matrix
    return None
size = 3
matrix = find_matrix_with_determinant(size, target_det=1)

if matrix is not None:
    print("Найдена матрица с определителем 1:")
    
    print(matrix)
    print("Определитель:", round(np.linalg.det(matrix)))
else:
    print("Матрица с определителем 1 не была найдена.")


Найдена матрица с определителем 1:
[[1 4 2]
 [2 2 3]
 [2 9 4]]
Определитель: 1
